local addonName, EJLoot = ...

EJLoot.FRAME_WIDTH = 420
EJLoot.FRAME_HEIGHT = 320
EJLoot.FRAME_PADDING_X = 12
EJLoot.SCROLLBAR_WIDTH = 26
EJLoot.ROW_LEFT_OFFSET = 8
EJLoot.LINK_LEFT_OFFSET = 20
EJLoot.CONTENT_WIDTH = EJLoot.FRAME_WIDTH - (EJLoot.FRAME_PADDING_X * 2) - EJLoot.SCROLLBAR_WIDTH
EJLoot.ROW_WIDTH = EJLoot.CONTENT_WIDTH - EJLoot.ROW_LEFT_OFFSET
EJLoot.LINK_ROW_WIDTH = EJLoot.CONTENT_WIDTH - EJLoot.LINK_LEFT_OFFSET
